### ISSUE TITLE
cant get addon buses to work

### ISSUE THREAD

**Issue by Alyxiate** [propstg/esx-blarglebus#46]
hi, im unable to get add-on buses to spawn, i have two buses in my CityBus config (bus and 18citaro) but only bus spawns, same when i try to do rentalbus and airbus in the Shuttle config

**Comment by Alyxiate** [comment]
this is how i have BusType.lua set up
![image](https://github.com/propstg/esx-blarglebus/assets/118795368/e50fd55c-5cba-4748-9c69-9648dc139f7d)

**Comment by Alyxiate** [comment]
oh i checked the readme it says i also have to add it to BusType table but there is no BusType table, how do i create one, sorry im new to fivem modding

**Comment by propstg** [comment]
Your screenshot is the BusType table. :) Lua calls `{}` tables instead of objects, for some reason.

I _think_ you might need to change both of them to give them a specific name, like
```
...
Airbus = {
    BusModel = 'airbus',
    ...
},
...
```

And then update the appropriate route config to say that you want to use a different bus for that route.

So to use BusType.Airbus on the airport route, you'd just change BusType.Shuttle to the new type in airport.lua (iirc you can only have one bus type per route)
![image](https://github.com/propstg/esx-blarglebus/assets/22607691/46ffcbe1-b85f-4613-abe5-8266ebc62da9)
